# Generated by Django 5.0.6 on 2024-05-18 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('fecha_limite_inscripcion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CarreraAnio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=1)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=12)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.carreraanio')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.alumno')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.carreraanio')),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.materia'),
        ),
    ]
