# Generated by Django 5.0.6 on 2024-05-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_alter_alumno_apellido_alter_alumno_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_limite_inscripcion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
